"""Add Covariance Table

Revision ID: 5e3c5d6e5fe5
Revises: 1ae1c0e4458b
Create Date: 2020-07-31 10:15:41.893767

"""

# revision identifiers, used by Alembic.
revision = '5e3c5d6e5fe5'
down_revision = '1ae1c0e4458b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker_covariance',
    sa.Column('symbol1', sa.String(length=10), nullable=False),
    sa.Column('symbol2', sa.String(length=10), nullable=False),
    sa.Column('covariance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('symbol1', 'symbol2')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticker_covariance')
    # ### end Alembic commands ###
