""" create Ticker Table

Revision ID: 69681a75150e
Revises: 51e2c29ad95
Create Date: 2020-07-21 09:10:35.606732

"""

# revision identifiers, used by Alembic.
revision = '69681a75150e'
down_revision = '51e2c29ad95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticker')
    # ### end Alembic commands ###
