"""Adds Market Capitalization into Ticker table

Revision ID: 809c8d83b89e
Revises: 69681a75150e
Create Date: 2020-07-22 17:42:39.367396

"""

# revision identifiers, used by Alembic.
revision = '809c8d83b89e'
down_revision = '69681a75150e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker', sa.Column('mcap', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker', 'mcap')
    # ### end Alembic commands ###
